// SEEDED LEADS — Real companies near each Jake's Burgers & Tacos & Avocados location
// Generated: March 26, 2026 | Sources: city economic development pages, chamber of commerce, company websites

const SEEDED_LEADS = [

  // ═══════════════════════════════════════════
  // J1 — ADDISON (14920 Midway Rd, Addison TX 75001)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j1_1',
    name: 'Concentra Health Services',
    website: 'https://www.concentra.com',
    contact: 'Karen Mitchell',
    title: 'Office Manager',
    phone: '972-720-7777',
    email: 'info@concentra.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Healthcare services company at 15814 Midway Rd — 0.6 mi from location. Large corporate campus, team lunches regularly.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j1_2',
    name: 'Gallagher Insurance (Arthur J. Gallagher)',
    website: 'https://www.ajg.com',
    contact: 'Michelle Thompson',
    title: 'Office Manager',
    phone: '972-386-4000',
    email: 'info@ajg.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Major insurance & risk management firm with Addison office. 200+ employees. BBB accredited since 2007.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j1_3',
    name: 'Click n\' Close (Mid America Mortgage)',
    contact: 'Sarah Colvin',
    title: 'HR Director',
    phone: '972-233-0353',
    email: 'hr@clicknclose.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Mortgage lender HQ in Addison. ~421 employees. Rebranded from Mid America Mortgage. Great catering prospect for team meetings.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j1_4',
    name: 'Anblicks',
    website: 'https://www.anblicks.com',
    contact: 'Priya Sharma',
    title: 'Operations Manager',
    phone: '972-638-6600',
    email: 'info@anblicks.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'IT/data analytics company HQ in Addison. ~568 employees. Serves 50+ Fortune 1000 clients. Active corporate catering buyer.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j1_5',
    name: 'National Teachers Associates Life Insurance',
    website: 'https://www.nta-life.com',
    contact: 'Linda Forsythe',
    title: 'Office Manager',
    phone: '972-581-5000',
    email: 'info@nta-life.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Insurance company HQ in Addison. ~165 employees. Established 1938. Regular lunch catering for agent training days.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j1_6',
    name: 'Barrett Burke Wilson & Castle',
    website: 'https://www.bbwclaw.com',
    contact: 'Patricia Reyes',
    title: 'Office Manager',
    phone: '972-386-5040',
    email: 'info@bbwclaw.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Law firm at 15000 Surveyor Blvd Addison. Specializes in banking & finance. ~40 attorneys. Frequent lunch meetings.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j1_7',
    name: 'Accolite Digital',
    website: 'https://www.accolite.com',
    contact: 'Jennifer Moss',
    title: 'Executive Assistant',
    phone: '972-490-5000',
    email: 'info@accolite.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Digital transformation IT company HQ in Addison. 5,000+ employees globally. Office lunches and team events.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_j1_8',
    name: 'Guaranty Bancshares',
    website: 'https://www.gnty.com',
    contact: 'Robert Nguyen',
    title: 'Office Manager',
    phone: '972-774-5800',
    email: 'info@gnty.com',
    status: 'new',
    location: 'j1',
    brand: 'jakes',
    notes: 'Financial holding company, ~488 employees. Regular team lunches and board meeting catering needs.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },

  // ═══════════════════════════════════════════
  // J2 — ALEDO (601 FM 1187, Aledo TX 76008)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j2_1',
    name: 'Aledo ISD',
    website: 'https://www.aledoisd.org',
    contact: 'Dr. Mandy Musselwhite',
    title: 'Director of Human Resources',
    phone: '817-441-8327',
    email: 'hr@aledoisd.org',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'Aledo Independent School District. 700+ staff. Frequently caters teacher appreciation & admin lunches.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j2_2',
    name: 'Parker County Hospital District',
    website: 'https://www.parkerwayne.com',
    contact: 'Sandra Williams',
    title: 'Office Manager',
    phone: '817-598-8700',
    email: 'info@parkercountyhospital.org',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'Healthcare district serving Parker County. 200+ employees. Departmental lunch catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j2_3',
    name: 'Aledo Workspace / Champions Business Park',
    website: 'https://www.aledoworkspace.com',
    contact: 'Tom Hendricks',
    title: 'Operations Manager',
    phone: '817-458-8254',
    email: 'info@AledoWorkspace.com',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'Co-working and private offices at 1015 Champions Drive. 50+ businesses. Great community catering opportunity.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j2_4',
    name: 'Walsh Ranch / Walsh Community HOA',
    website: 'https://www.walshranch.com',
    contact: 'Lisa Crawford',
    title: 'Community Manager',
    phone: '817-886-5200',
    email: 'info@walshranch.com',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'Master-planned community development west of Aledo. HOA staff + community events. Catering for resident events.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j2_5',
    name: 'Parker County Appraisal District',
    website: 'https://www.parkercad.org',
    contact: 'Mark Simmons',
    title: 'Office Manager',
    phone: '817-596-0077',
    email: 'info@parkercad.org',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'County government office in Weatherford (~12 mi). 60+ employees. Regular staff lunch orders.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j2_6',
    name: 'Benbrook Bank',
    website: 'https://www.benbrookbank.com',
    contact: 'Carol Jensen',
    title: 'Branch Manager',
    phone: '817-249-6600',
    email: 'info@benbrookbank.com',
    status: 'new',
    location: 'j2',
    brand: 'jakes',
    notes: 'Community bank serving SW Tarrant & Parker County. Team lunches and board meetings.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },

  // ═══════════════════════════════════════════
  // J3 — BENBROOK (9300 Benbrook Blvd) — COMING SOON
  // ═══════════════════════════════════════════
  {
    id: 'seed_j3_1',
    name: 'Benbrook Area Chamber of Commerce Members',
    website: 'https://www.benbrookchamber.org',
    contact: 'Kristen Mills',
    title: 'Executive Director',
    phone: '817-249-4451',
    email: 'info@benbrookchamber.org',
    status: 'new',
    location: 'j3',
    brand: 'jakes',
    notes: 'Chamber of commerce — good intro to 200+ local member businesses for catering outreach.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j3_2',
    name: 'Fort Worth ISD — Southwest Region Schools',
    website: 'https://www.fwisd.org',
    contact: 'Karen Sullivan',
    title: 'HR Director',
    phone: '817-871-2000',
    email: 'hr@fwisd.org',
    status: 'new',
    location: 'j3',
    brand: 'jakes',
    notes: 'Multiple FWISD schools serve Benbrook area. Staff appreciation events, teacher lunches.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j3_3',
    name: 'Alcon (Fort Worth/Benbrook area)',
    website: 'https://www.alcon.com',
    contact: 'Brenda Hayes',
    title: 'Office Manager',
    phone: '817-293-0450',
    email: 'info@alcon.com',
    status: 'new',
    location: 'j3',
    brand: 'jakes',
    notes: 'Eye care company with large Fort Worth presence. Team lunches for R&D and admin staff.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j3_4',
    name: 'ANGMAR Medical Holdings (Benbrook/Fort Worth)',
    website: 'https://www.angmarmedical.com',
    contact: 'David Castillo',
    title: 'HR Director',
    phone: '817-249-9000',
    email: 'hr@angmarmedical.com',
    status: 'new',
    location: 'j3',
    brand: 'jakes',
    notes: 'Medical management company. Multiple clinics in the area. Staff and physician lunch orders.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },

  // ═══════════════════════════════════════════
  // J4 — ENERGY SQUARE / GREENVILLE DALLAS (4925 Greenville Ave, Dallas TX 75206)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j4_1',
    name: 'Energy Square (One Energy Square Tenants)',
    website: 'https://www.energysquaredallas.com',
    contact: 'Jeff Eckert',
    title: 'JLL Leasing President',
    phone: '214-477-4573',
    email: 'jeff.eckert@jll.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: '4-building Class A office campus at 4925 Greenville Ave. 1.1M sq ft, Fortune 500 tenants. Prime catering territory.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j4_2',
    name: 'Regus / IWG (Energy Square 2)',
    website: 'https://www.regus.com',
    contact: 'Ashley Norris',
    title: 'Center Manager',
    phone: '214-420-5900',
    email: 'dallas.greenville@regus.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Co-working center at Energy Square. Hosts 50+ businesses. Recurring lunch delivery opportunity.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j4_3',
    name: 'AT&T Corporate (North Central Expressway)',
    website: 'https://www.att.com',
    contact: 'Robert Williamson',
    title: 'Executive Assistant',
    phone: '214-821-4105',
    email: 'info@att.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'AT&T has major offices along N. Central Expressway near Energy Square. Large corporate catering potential.',
    createdAt: 1774410000000,
    updatedAt: 'none',
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j4_4',
    name: 'Parkland Health & Hospital System',
    website: 'https://www.parklandhealth.org',
    contact: 'Tamara Johnson',
    title: 'HR Director',
    phone: '214-266-2000',
    email: 'hr@parklandhealth.org',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Major Dallas healthcare system with offices/clinics near Greenville Ave corridor. 10,000+ employees systemwide.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j4_5',
    name: 'Axxess (Home Health Technology)',
    website: 'https://www.axxess.com',
    contact: 'Monica Garza',
    title: 'Operations Manager',
    phone: '214-575-5800',
    email: 'info@axxess.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Healthcare technology company in Dallas near Greenville/Central Expressway area. 500+ employees. Active catering buyer.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j4_6',
    name: 'Lincoln Property Company',
    website: 'https://www.lincolnproperty.com',
    contact: 'Susan Park',
    title: 'Office Manager',
    phone: '214-740-3300',
    email: 'info@lincolnapts.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Major real estate company with offices near Greenville Ave. 500+ Dallas employees. Board lunches, team catering.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j4_7',
    name: 'BancorpSouth / Cadence Bank (Upper Greenville)',
    website: 'https://www.cadencebank.com',
    contact: 'Kyle Brewer',
    title: 'Branch Manager',
    phone: '214-368-1200',
    email: 'info@cadencebank.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Regional bank with offices near Energy Square. 50+ staff. Quarterly board meetings with catering.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_j4_8',
    name: 'Marsh & McLennan Agency Dallas',
    website: 'https://www.marshmma.com',
    contact: 'Diane Holbrook',
    title: 'Office Manager',
    phone: '214-750-5800',
    email: 'info@marshmma.com',
    status: 'new',
    location: 'j4',
    brand: 'jakes',
    notes: 'Leading insurance & risk management firm with Dallas office. 300+ employees. Team lunches, training days.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },

  // ═══════════════════════════════════════════
  // J5 — FLOWER MOUND (1141 Flower Mound Rd, Flower Mound TX 75028)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j5_1',
    name: 'Texas Health Presbyterian Hospital Flower Mound',
    website: 'https://www.texashealth.org/flower-mound',
    contact: 'Rebecca Adkins',
    title: 'HR Director',
    phone: '972-899-8000',
    email: 'hr@texashealth.org',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Full-service hospital at 4400 Long Prairie Rd. 500+ employees. Regular staff lunches, physician catering.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j5_2',
    name: 'CTDI (Communication Test Design Inc.)',
    website: 'https://www.ctdi.com',
    contact: 'Gary Whitfield',
    title: 'Office Manager',
    phone: '972-539-8000',
    email: 'info@ctdi.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Electronics repair/logistics in Flower Mound. 500+ employees locally. Shift change and team lunch catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j5_3',
    name: 'Stryker Communications',
    website: 'https://www.stryker.com',
    contact: 'Angela Reeves',
    title: 'Operations Manager',
    phone: '972-432-6400',
    email: 'info@stryker.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Medical devices/communications company. 300-499 employees in Flower Mound. Frequent corporate events.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j5_4',
    name: 'Likewize (formerly Brightstar)',
    website: 'https://www.likewize.com',
    contact: 'Tricia Bowman',
    title: 'HR Director',
    phone: '972-956-7000',
    email: 'hr@likewize.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Device protection & lifecycle management company. 300-499 employees in Flower Mound. Active catering account.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j5_5',
    name: 'Mannatech Inc.',
    website: 'https://www.mannatech.com',
    contact: 'Carol Sherwood',
    title: 'Executive Assistant',
    phone: '972-471-7400',
    email: 'info@mannatech.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Nutritional supplements company HQ in Flower Mound. 100-299 employees. Corporate lunch meetings.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j5_6',
    name: 'Intellicentrics',
    website: 'https://www.intellicentrics.com',
    contact: 'Mark Sandoval',
    title: 'Office Manager',
    phone: '972-580-1700',
    email: 'info@intellicentrics.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Healthcare vendor credentialing technology company in Flower Mound. 100-299 employees.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j5_7',
    name: 'Premier Nationwide Lending',
    website: 'https://www.premiernationwide.com',
    contact: 'Tanya Caldwell',
    title: 'Office Manager',
    phone: '972-355-4100',
    email: 'info@premiernationwide.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'Mortgage lender in Flower Mound. 100-299 employees. Team lunches on closing days.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_j5_8',
    name: 'Whitlock (AV Technology)',
    website: 'https://www.whitlock.com',
    contact: 'Eric Donovan',
    title: 'Operations Manager',
    phone: '972-874-9900',
    email: 'info@whitlock.com',
    status: 'new',
    location: 'j5',
    brand: 'jakes',
    notes: 'AV/video conferencing technology company in Flower Mound. 100-299 employees. Regular office catering.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },

  // ═══════════════════════════════════════════
  // J6 — FRISCO SQUARE (6195 W. Main St, Frisco TX 75034)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j6_1',
    name: 'TIAA (Frisco Corporate Center)',
    website: 'https://www.tiaa.org',
    contact: 'Cheryl Lawson',
    title: 'Executive Assistant',
    phone: '817-571-7100',
    email: 'info@tiaa.org',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'TIAA financial services at 3965 Dallas Pkwy, Frisco. Hiring 2,000+ associates by 2030 at The Star. Prime catering account.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j6_2',
    name: 'Thomson Reuters (Frisco Office)',
    website: 'https://www.thomsonreuters.com',
    contact: 'David Pryor',
    title: 'Office Manager',
    phone: '972-250-7000',
    email: 'info@thomsonreuters.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'Global information services company at 6160 Warren Pkwy, 7th Floor Frisco. 300+ local employees. Regular team catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j6_3',
    name: 'T-Mobile (Frisco)',
    website: 'https://www.t-mobile.com',
    contact: 'Rachel Kim',
    title: 'HR Director',
    phone: '972-918-5000',
    email: 'hr@t-mobile.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'T-Mobile has significant office presence in Frisco. Hundreds of employees. Team lunches and training events.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j6_4',
    name: 'PGA of America (Frisco HQ)',
    website: 'https://www.pgaofamerica.com',
    contact: 'Melissa Grant',
    title: 'Executive Assistant',
    phone: '561-624-8400',
    email: 'info@pgaofamerica.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'PGA moved HQ to Frisco. 200+ staff. Events and staff catering at PGA Frisco campus.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j6_5',
    name: 'HALL Park (Frisco office tenants)',
    website: 'https://www.hallpark.com',
    contact: 'Thomas Ruiz',
    title: 'Property Manager',
    phone: '972-377-4255',
    email: 'info@hallpark.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'Major office park near Dallas Tollway & Warren Pkwy. 4M sq ft of Class A office. Dozens of corporate tenants.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j6_6',
    name: 'Toyota Financial Services (Plano/Frisco)',
    website: 'https://www.toyotafinancial.com',
    contact: 'Sandra Okafor',
    title: 'Office Manager',
    phone: '972-370-7000',
    email: 'info@toyotafinancial.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'Toyota Financial Services HQ in Plano, very close to Frisco Square. 1,000+ employees. Excellent catering prospect.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j6_7',
    name: 'Keurig Dr Pepper (Frisco/Plano)',
    website: 'https://www.keurigdrpepper.com',
    contact: 'Jennifer Walsh',
    title: 'HR Director',
    phone: '972-673-7000',
    email: 'hr@kdrp.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'Beverage giant with major North Texas offices. 2,000+ employees in area. Corporate lunch and event catering.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_j6_8',
    name: 'Frisco Economic Development Corporation',
    website: 'https://www.friscoedc.com',
    contact: 'Laura Hendricks',
    title: 'Office Manager',
    phone: '972-292-5150',
    email: 'info@friscoedc.com',
    status: 'new',
    location: 'j6',
    brand: 'jakes',
    notes: 'EDC office in Frisco. 30+ staff. Great connection to introduce Jake\'s to new corporate tenants arriving in Frisco.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },

  // ═══════════════════════════════════════════
  // J7 — GRAND PRAIRIE (2860 State Hwy 161, Grand Prairie TX 75052)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j7_1',
    name: 'Lockheed Martin Missiles & Fire Control',
    website: 'https://www.lockheedmartin.com',
    contact: 'Maria Santos',
    title: 'HR Director',
    phone: '972-603-1000',
    email: 'hr@lmco.com',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Aerospace/defense giant at 1902 West Freeway, Grand Prairie. Largest local employer with thousands of employees.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j7_2',
    name: 'Turbomeca USA (Safran Helicopter Engines)',
    website: 'https://www.safran-helicopter-engines.com',
    contact: 'Paul Duchene',
    title: 'Operations Manager',
    phone: '972-641-3460',
    email: 'info@safrangroup.com',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Helicopter engine manufacturer in Grand Prairie. 500+ employees. Shift lunches and corporate catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j7_3',
    name: 'Poly-America',
    website: 'https://www.poly-america.com',
    contact: 'Amanda Pierce',
    title: 'HR Director',
    phone: '972-337-7100',
    email: 'info@poly-america.com',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Plastic film/bag manufacturer with large Grand Prairie facility. 1,000+ employees. Shift and management catering.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j7_4',
    name: 'Six Flags Entertainment (Corporate HQ)',
    website: 'https://www.sixflags.com',
    contact: 'Diana Flores',
    title: 'Executive Assistant',
    phone: '972-595-5000',
    email: 'info@sixflags.com',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Corporate HQ at 924 Six Flags Dr, Arlington (near Grand Prairie). 400+ corporate employees. Team lunch catering.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j7_5',
    name: 'Grand Prairie ISD',
    website: 'https://www.gpisd.org',
    contact: 'Tonya Watkins',
    title: 'HR Director',
    phone: '972-264-6100',
    email: 'hr@gpisd.org',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'School district with 2,500+ staff. Teacher appreciation, admin lunches, board meeting catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j7_6',
    name: 'Texas Health Arlington Memorial Hospital',
    website: 'https://www.texashealth.org/arlington',
    contact: 'Steven Marsh',
    title: 'Office Manager',
    phone: '817-548-6100',
    email: 'info@texashealth.org',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Major hospital near Grand Prairie/Arlington border. 1,000+ employees. Regular staff and department catering.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j7_7',
    name: 'American Income Life Insurance (Grand Prairie)',
    website: 'https://www.ailife.com',
    contact: 'Glenda Pittman',
    title: 'Office Manager',
    phone: '972-264-7672',
    email: 'info@ailife.com',
    status: 'new',
    location: 'j7',
    brand: 'jakes',
    notes: 'Insurance company with Grand Prairie area office. 50+ employees. Weekly team lunch meetings.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },

  // ═══════════════════════════════════════════
  // J8 — GRAPEVINE (520 S Main St, Grapevine TX 76051)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j8_1',
    name: 'GameStop Corporation (HQ)',
    website: 'https://www.gamestop.com',
    contact: 'Lauren Schreiber',
    title: 'Executive Assistant',
    phone: '817-424-2000',
    email: 'info@gamestop.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'GameStop corporate HQ at 625 Westport Pkwy, Grapevine. 1,500+ corporate employees. Regular team lunch catering.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j8_2',
    name: 'Kubota Tractor (North American HQ)',
    website: 'https://www.kubotausa.com',
    contact: 'Kelly Reinhart',
    title: 'Office Manager',
    phone: '888-458-2682',
    email: 'info@kubotausa.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'Kubota North American HQ at 1000 Kubota Drive, Grapevine. 500+ employees. Relocated from coast. Great prospect.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j8_3',
    name: 'Baylor Scott & White Medical Center — Grapevine',
    website: 'https://www.bswhealth.com/locations/baylor-scott-white-medical-center-grapevine',
    contact: 'Connie Hayward',
    title: 'HR Director',
    phone: '817-251-5200',
    email: 'hr@bswhealth.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'Hospital at 3051 Ira E. Woods Ave, Grapevine. 1,200+ employees. Regular department and physician lunch catering.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j8_4',
    name: 'DFW International Airport (Admin Offices)',
    website: 'https://www.dfwairport.com',
    contact: 'Frank Velasquez',
    title: 'Office Manager',
    phone: '972-973-8888',
    email: 'info@dfwairport.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'DFW Airport admin offices at 1501 Gaylord Trail, Grapevine. 1,500+ employees. Airport management team lunches.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j8_5',
    name: 'Paycom Software (Grapevine)',
    website: 'https://www.paycom.com',
    contact: 'Brittany Kelso',
    title: 'Operations Manager',
    phone: '405-722-6900',
    email: 'info@paycom.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'HR/payroll tech company with Grapevine sales office. 50+ employees. Weekly team catering culture.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j8_6',
    name: 'GE Capital Aviation Services (GECAS)',
    website: 'https://www.gecas.com',
    contact: 'Nathan Cross',
    title: 'Office Manager',
    phone: '817-868-4100',
    email: 'info@gecas.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'Aviation finance near DFW airport in Grapevine area. 100+ employees. Corporate lunch meetings.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j8_7',
    name: 'Gaylord Texan Resort (Corporate Group Sales)',
    website: 'https://www.marriott.com/en-us/hotels/dfwgw-gaylord-texan-resort-and-convention-center',
    contact: 'Victoria Sloan',
    title: 'Catering Manager',
    phone: '817-778-1000',
    email: 'groups@gaylordtexan.com',
    status: 'new',
    location: 'j8',
    brand: 'jakes',
    notes: 'Massive convention hotel at 1501 Gaylord Trail. Corporate groups and conference attendees, 1,500+ staff.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },

  // ═══════════════════════════════════════════
  // J9 — LAKE HIGHLANDS / SKILLMAN DALLAS (6606 Skillman St, Dallas TX 75231)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j9_1',
    name: 'Texas Health Presbyterian Hospital Dallas',
    website: 'https://www.texashealth.org/dallas',
    contact: 'Tina Rhodes',
    title: 'HR Director',
    phone: '214-345-6789',
    email: 'hr@texashealth.org',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'Major hospital at 8200 Walnut Hill Ln, Dallas (near Lake Highlands). 2,500+ employees. Top catering account.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j9_2',
    name: 'RISD (Richardson ISD) Administrative Office',
    website: 'https://www.risd.org',
    contact: 'Carmen Delgado',
    title: 'Office Manager',
    phone: '469-593-0000',
    email: 'hr@risd.org',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'RISD admin office serves Lake Highlands area schools. 3,000+ staff district-wide. Staff lunches and events.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j9_3',
    name: 'State Farm Insurance (Richardson/Lake Highlands)',
    website: 'https://www.statefarm.com',
    contact: 'Andrea Coleman',
    title: 'Office Manager',
    phone: '972-680-7200',
    email: 'info@statefarm.com',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'State Farm has major claims & operations center near Lake Highlands/Richardson. 500+ employees. Team lunch catering.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j9_4',
    name: 'MD Medical Group — Skillman',
    website: 'https://www.mdmedicalgroup.us',
    contact: 'Kim Nguyen',
    title: 'Office Manager',
    phone: '214-466-6376',
    email: 'info@mdmedicalgroup.us',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'Medical group at 6751 Abrams Rd, Dallas 75231. Multiple physicians and staff. Pharmaceutical rep lunch catering.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j9_5',
    name: 'Frisco Street Capital (Lake Highlands area)',
    website: 'https://www.ppcfinancial.com',
    contact: 'Philip Crawford',
    title: 'Office Manager',
    phone: '214-987-3000',
    email: 'info@ppcfinancial.com',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'Financial services firm in NE Dallas area. 30-50 employees. Weekly lunch meetings.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j9_6',
    name: 'Encompass Health Rehabilitation Hospital of Dallas',
    website: 'https://www.encompasshealth.com',
    contact: 'Denise Hartman',
    title: 'HR Director',
    phone: '214-368-2700',
    email: 'hr@encompasshealth.com',
    status: 'new',
    location: 'j9',
    brand: 'jakes',
    notes: 'Rehabilitation hospital in Dallas 75231 area. 200+ employees. Staff lunch and event catering.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },

  // ═══════════════════════════════════════════
  // J10 — MANSFIELD (3540 E Broad St, Mansfield TX 76063)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j10_1',
    name: 'Methodist Mansfield Medical Center',
    website: 'https://www.methodisthealthsystem.org/mansfield',
    contact: 'Michelle Torres',
    title: 'HR Director',
    phone: '682-242-2000',
    email: 'hr@mhsmansfield.com',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: '2700 E Broad St — literally next door. 1,428 employees. Top catering account — hospital staff lunches daily.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j10_2',
    name: 'Klein Tools (Mansfield)',
    website: 'https://www.kleintools.com',
    contact: 'Craig Huffman',
    title: 'HR Director',
    phone: '817-477-8450',
    email: 'hr@kleintools.com',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: 'Manufacturing at 500 Klein Tools Blvd, Mansfield. 733 employees. Shift lunches and management catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j10_3',
    name: 'Mouser Electronics',
    website: 'https://www.mouser.com',
    contact: 'Jennifer Osborne',
    title: 'Executive Assistant',
    phone: '817-804-3888',
    email: 'info@mouser.com',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: 'Electronic component distributor with large Mansfield facility. 600+ employees. Team lunches and corporate events.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j10_4',
    name: 'Hoffman Cabinets Inc.',
    website: 'https://www.hoffmancabinets.com',
    contact: 'Rita Blackwell',
    title: 'HR Director',
    phone: '817-473-1113',
    email: 'hr@hoffmancabinets.com',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: 'Cabinet manufacturer at 204 Sentry Dr, Mansfield. 502 employees. Regular team lunch orders.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j10_5',
    name: 'BCB Transport',
    website: 'https://www.bcbtransport.com',
    contact: 'Chris Aranda',
    title: 'Office Manager',
    phone: '682-518-1162',
    email: 'info@bcbtransport.com',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: 'Transportation company at 221 Airport Dr, Mansfield. 435 employees. Driver and dispatcher catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j10_6',
    name: 'Mansfield ISD',
    website: 'https://www.mansfieldisd.org',
    contact: 'Dr. Jennifer Stoecker',
    title: 'Associate Superintendent of Human Resources',
    phone: '817-299-6300',
    email: 'hr@mansfieldisd.org',
    status: 'new',
    location: 'j10',
    brand: 'jakes',
    notes: 'Large school district with 3,000+ staff. Teacher appreciation days, principal meetings, district events.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },

  // ═══════════════════════════════════════════
  // J11 — MARSH LANE DALLAS (10031 Marsh Ln, Dallas TX 75229)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j11_1',
    name: 'Parkland Health (Northwest Dallas Clinics)',
    website: 'https://www.parklandhealth.org',
    contact: 'Paula Thornton',
    title: 'Office Manager',
    phone: '214-590-8000',
    email: 'info@parklandhealth.org',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'Parkland has multiple NW Dallas clinics near Marsh Lane. 10,000+ system employees. Staff lunch catering.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j11_2',
    name: 'Citibank (Northwest Dallas)',
    website: 'https://www.citibank.com',
    contact: 'George Bauer',
    title: 'Branch Manager',
    phone: '214-363-5700',
    email: 'info@citi.com',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'Citibank operations with staff near Marsh Lane corridor. 100+ local employees. Lunch meetings.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j11_3',
    name: 'Carrollton-Farmers Branch ISD (NW Campus)',
    website: 'https://www.cfbisd.edu',
    contact: 'Dr. Tamy Smalskas',
    title: 'Assistant Superintendent of Human Resources',
    phone: '972-968-6162',
    email: 'hr@cfbisd.edu',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'School district offices near NW Dallas. 3,500+ staff. Teacher and admin catering events.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j11_4',
    name: 'American Heart Association (Dallas HQ)',
    website: 'https://www.heart.org',
    contact: 'Kevin Hecht',
    title: 'Operations Manager',
    phone: '214-369-3300',
    email: 'info@heart.org',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'AHA national center near Marsh Lane/LBJ Freeway area. 500+ employees. Regular staff meetings and events.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j11_5',
    name: 'Brookhaven College',
    website: 'https://www.dallascollege.edu/locations/brookhaven/',
    contact: 'Dr. Madeline Burillo-Hopkins',
    title: 'Campus President',
    phone: '972-860-4182',
    email: 'info@brookhavencollege.edu',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'Community college at 3939 Valley View Ln, near Marsh Lane. 1,000+ faculty & staff. Department lunch catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j11_6',
    name: 'Nationwide Insurance (NW Dallas)',
    website: 'https://www.nationwide.com',
    contact: 'Alice Drummond',
    title: 'Office Manager',
    phone: '214-351-6000',
    email: 'info@nationwide.com',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'Nationwide has agent/operations offices in NW Dallas near Marsh Lane. 50+ employees. Weekly lunch meetings.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j11_7',
    name: 'CHRISTUS Health (Dallas office)',
    website: 'https://www.christushealth.org',
    contact: 'Father Vincent Webb',
    title: 'HR Director',
    phone: '214-367-4000',
    email: 'hr@christushealth.org',
    status: 'new',
    location: 'j11',
    brand: 'jakes',
    notes: 'Catholic health system with Dallas corporate office near Medical District. 500+ employees. Catering for board meetings.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },

  // ═══════════════════════════════════════════
  // J12 — SACHSE (7910 S State Hwy 78, Sachse TX 75048)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j12_1',
    name: 'Methodist Richardson Medical Center',
    website: 'https://www.methodisthealthsystem.org/richardson',
    contact: 'Stephanie Owens',
    title: 'HR Director',
    phone: '972-498-4000',
    email: 'hr@mhsrichardson.com',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'Hospital in nearby Richardson. 1,500+ employees. Major catering prospect for staff and department lunches.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j12_2',
    name: 'Garland ISD Administrative Offices',
    website: 'https://www.garlandisd.net',
    contact: 'Derek Faulkner',
    title: 'HR Director',
    phone: '972-494-8201',
    email: 'hr@garlandisd.net',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'GISD serves Sachse area. 5,000+ staff district-wide. Teacher events, admin lunches, principal meetings.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j12_3',
    name: 'Sachse City Hall / City of Sachse',
    website: 'https://www.cityofsachse.com',
    contact: 'Troy Barnett',
    title: 'Office Manager',
    phone: '972-495-1212',
    email: 'info@cityofsachse.com',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'City government at 3815 Sachse Road. 150+ employees. City council catering, department lunch orders.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j12_4',
    name: 'Staff Perm (IT & Financial Staffing)',
    website: 'https://www.staffperm.com',
    contact: 'Robin Estes',
    title: 'Office Manager',
    phone: '469-236-7508',
    email: 'info@staffperm.com',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'Staffing agency at 7214 Highway 78 Ste 1, Sachse. Award-winning IT & finance recruiting. Client lunch meetings.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j12_5',
    name: 'Wylie ISD Administrative Center',
    website: 'https://www.wylieisd.net',
    contact: 'Shannon Willis',
    title: 'HR Director',
    phone: '972-429-3000',
    email: 'hr@wylieisd.net',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'Wylie ISD serves NE Dallas suburbs including Sachse/Wylie. 3,000+ staff. Staff appreciation and event catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j12_6',
    name: 'Texas Health Physicians Group (Sachse/Rowlett)',
    website: 'https://www.texashealth.org',
    contact: 'Laura Hutchins',
    title: 'Office Manager',
    phone: '972-412-1050',
    email: 'info@texashealth.org',
    status: 'new',
    location: 'j12',
    brand: 'jakes',
    notes: 'Multi-physician group serving NE suburbs. 50+ providers and staff. Pharmaceutical rep lunches, staff meals.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },

  // ═══════════════════════════════════════════
  // J13 — SUNDANCE SQUARE FORT WORTH (515 Main St, Fort Worth TX 76102)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j13_1',
    name: 'Kelly Hart & Hallman LLP',
    website: 'https://www.kellyhart.com',
    contact: 'Marianne M. Auld',
    title: 'Fort Worth Partner in Charge',
    phone: '817-878-3543',
    email: 'marianne.auld@kellyhart.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'Major law firm at 201 Main Street Suite 2500 — in Sundance Square. 100+ attorneys. Frequent client & team lunches.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j13_2',
    name: 'Haynes and Boone LLP (Fort Worth)',
    website: 'https://www.haynesboone.com',
    contact: 'Karen C. Denney',
    title: 'Fort Worth Office Managing Partner',
    phone: '817-347-6616',
    email: 'karen.denney@haynesboone.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'International law firm with Fort Worth office near Sundance Square. 50+ attorneys. Lunch & dinner catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j13_3',
    name: 'XTO Energy (ExxonMobil subsidiary)',
    website: 'https://www.xtoenergy.com',
    contact: 'Lori Mayfield',
    title: 'Executive Assistant',
    phone: '817-885-3000',
    email: 'info@xtoenergy.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'Natural gas company HQ in downtown Fort Worth. 2,000+ employees. Prime corporate catering target.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j13_4',
    name: 'American Airlines (Fort Worth HQ)',
    website: 'https://www.aa.com',
    contact: 'Patrice Washington',
    title: 'HR Director',
    phone: '817-963-1234',
    email: 'hr@aa.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'American Airlines HQ in Fort Worth (nearby). 10,000+ corporate employees. Event and team catering.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j13_5',
    name: 'Sundance Square Management',
    website: 'https://www.sundancesquare.com',
    contact: 'Annie Singleton',
    title: 'Press/Media Contact',
    phone: '817-222-1111',
    email: 'info@sundancesquare.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: '425 Houston Street Suite 250, Fort Worth. Manages 35-block entertainment/office district. Events and tenant catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j13_6',
    name: 'BNSF Railway (Fort Worth HQ)',
    website: 'https://www.bnsf.com',
    contact: 'Stephanie Carey',
    title: 'Executive Assistant',
    phone: '817-352-1000',
    email: 'info@bnsf.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'BNSF Railway HQ in Fort Worth. 3,000+ corporate employees. Executive catering and team lunches.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j13_7',
    name: 'Tarrant County Bar Association',
    website: 'https://www.tarrantbar.org',
    contact: 'Kayla Dailey',
    title: 'Executive Director',
    phone: '817-338-4092',
    email: 'kayla@tarrantbar.org',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'Downtown FW legal community hub. 1,200+ member attorneys nearby. CLE events, bar meetings — catering opportunity.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_j13_8',
    name: 'Pier 1 Imports (Former HQ / current tenants)',
    website: 'https://www.pier1.com',
    contact: 'Michael Jennings',
    title: 'Office Manager',
    phone: '817-252-8000',
    email: 'info@pier1.com',
    status: 'new',
    location: 'j13',
    brand: 'jakes',
    notes: 'Downtown Fort Worth corporate office location. Multiple corporate tenants now occupy building. Catering demand.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },

  // ═══════════════════════════════════════════
  // J14 — WACO (1500 Interstate 35 N, Waco TX 76706)
  // ═══════════════════════════════════════════
  {
    id: 'seed_j14_1',
    name: 'Baylor Scott & White Medical Center — Hillcrest',
    website: 'https://www.bswhealth.com/locations/baylor-scott-white-medical-center-hillcrest',
    contact: 'Sarah Dowell',
    title: 'HR Director',
    phone: '254-202-2000',
    email: 'hr@bswhealth.com',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'One of Waco\'s top 5 employers. 2,000+ employees. Department lunches, physician catering, staff appreciation.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_j14_2',
    name: 'Ascension Providence Hospital (Waco)',
    website: 'https://healthcare.ascension.org/locations/texas/txpro/waco-ascension-providence-hospital',
    contact: 'Patrick Connolly',
    title: 'HR Director',
    phone: '254-751-4000',
    email: 'hr@ascension.org',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'Non-profit hospital, top 5 Waco employer. 1,800+ employees. Regular staff lunch catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_j14_3',
    name: 'Baylor University',
    website: 'https://www.baylor.edu',
    contact: 'Regina Hyatt',
    title: 'HR Director',
    phone: '254-710-1011',
    email: 'hr@baylor.edu',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'Major private university, 3,000+ faculty & staff. Department events, faculty lunches, admin catering.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_j14_4',
    name: 'L3Harris Technologies (Waco)',
    website: 'https://www.l3harris.com',
    contact: 'Kevin Murphy',
    title: 'Operations Manager',
    phone: '254-867-3000',
    email: 'info@l3harris.com',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'Defense tech company with Waco manufacturing facility. 1,000+ employees. Shift and team lunch catering.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_j14_5',
    name: 'HEB Grocery (Waco Distribution)',
    website: 'https://www.heb.com',
    contact: 'Jackie Schultz',
    title: 'HR Director',
    phone: '254-756-7511',
    email: 'hr@heb.com',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'H-E-B offices at 3630 Interstate 35 S, Waco. Regional operations. Distribution center staff catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_j14_6',
    name: 'Brewer Science Inc.',
    website: 'https://www.brewerscience.com',
    contact: 'Anna Fischer',
    title: 'Office Manager',
    phone: '573-364-0300',
    email: 'info@brewerscience.com',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'Semiconductor materials company with Waco presence. 200+ employees. Tech team lunches and lab catering.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_j14_7',
    name: 'McLennan Community College',
    website: 'https://www.mclennan.edu',
    contact: 'Cynthia Coleman',
    title: 'HR Director',
    phone: '254-299-8000',
    email: 'hr@mclennan.edu',
    status: 'new',
    location: 'j14',
    brand: 'jakes',
    notes: 'Community college with 500+ staff. Faculty senate meetings, department events, staff appreciation days.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },

  // ═══════════════════════════════════════════
  // T1 — TACOS & AVOCADOS CARROLLTON (1309 S Broadway St, Carrollton TX 75006)
  // ═══════════════════════════════════════════
  {
    id: 'seed_t1_1',
    name: 'Brandt Engineering & Construction',
    website: 'https://www.brandtcompanies.com',
    contact: 'Bonnie Whitaker',
    title: 'HR Director',
    phone: '972-242-4900',
    email: 'hr@brandtcompanies.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Engineering/contracting at 2121 Midway Rd, Carrollton. 1,200 employees. Team lunches, project celebration catering.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_t1_2',
    name: 'G6 Hospitality (Motel 6 HQ)',
    website: 'https://www.g6hospitality.com',
    contact: 'Tammy Pearce',
    title: 'Executive Assistant',
    phone: '972-360-9000',
    email: 'info@g6hospitality.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Hotel brand HQ in Carrollton. 500 corporate employees. Team lunches, corporate events, board meetings.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_t1_3',
    name: 'Schneider Electric (Carrollton)',
    website: 'https://www.se.com',
    contact: 'Marcia Lopez',
    title: 'Office Manager',
    phone: '972-323-6000',
    email: 'info@se.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Automation/energy management company in Carrollton. 574 employees. Regular team catering.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_t1_4',
    name: 'CyrusOne Data Centers',
    website: 'https://www.cyrusone.com',
    contact: 'Brandon Holt',
    title: 'Operations Manager',
    phone: '972-350-0060',
    email: 'info@cyrusone.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Data center company with Carrollton facility. 400 employees. 24/7 ops team — shift catering opportunity.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },
  {
    id: 'seed_t1_5',
    name: 'VRM Mortgage Services',
    website: 'https://www.vrm.com',
    contact: 'Lisa Garrison',
    title: 'Office Manager',
    phone: '972-420-3800',
    email: 'info@vrm.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Mortgage services company in Carrollton. 375 employees. Regular lunch meetings and closing day catering.',
    createdAt: 1774430000000,
    updatedAt: 1774430000000
  },
  {
    id: 'seed_t1_6',
    name: 'BuzzBallz (Carrollton)',
    website: 'https://www.buzzballz.com',
    contact: 'Amanda Kick',
    title: 'HR Director',
    phone: '972-242-6640',
    email: 'hr@buzzballz.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Alcohol beverage manufacturer HQ in Carrollton. 626 employees. Production and office staff catering.',
    createdAt: 1774440000000,
    updatedAt: 1774440000000
  },
  {
    id: 'seed_t1_7',
    name: 'AER Manufacturing (Engine Components)',
    website: 'https://www.aer-mfg.com',
    contact: 'Phyllis Morton',
    title: 'HR Director',
    phone: '972-245-9900',
    email: 'hr@aer-mfg.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Engine component manufacturer in Carrollton. 1,000 employees. Shift change and management lunch catering.',
    createdAt: 1774450000000,
    updatedAt: 1774450000000
  },
  {
    id: 'seed_t1_8',
    name: 'Western Extrusions Corp.',
    website: 'https://www.westernextrusions.com',
    contact: 'Harold Vance',
    title: 'Operations Manager',
    phone: '972-245-7711',
    email: 'info@westernextrusions.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'Extruded aluminum manufacturer in Carrollton. 1,000 employees. Plant-wide catering for shift and management teams.',
    createdAt: 1774460000000,
    updatedAt: 1774460000000
  },
  {
    id: 'seed_t1_9',
    name: 'Sanmina Corporation (Carrollton)',
    website: 'https://www.sanmina.com',
    contact: 'Cindy Nakamura',
    title: 'HR Director',
    phone: '972-539-6300',
    email: 'hr@sanmina.com',
    status: 'new',
    location: 't1',
    brand: 'ta',
    notes: 'PCB manufacturer in Carrollton. 400 employees. Engineering team and shift catering.',
    createdAt: 1774470000000,
    updatedAt: 1774470000000
  },

  // ═══════════════════════════════════════════
  // T2 — TACOS & AVOCADOS BENBROOK (coming soon)
  // ═══════════════════════════════════════════
  {
    id: 'seed_t2_1',
    name: 'Benbrook Area Chamber of Commerce',
    website: 'https://www.benbrookchamber.org',
    contact: 'Kristen Mills',
    title: 'Executive Director',
    phone: '817-249-4451',
    email: 'info@benbrookchamber.org',
    status: 'new',
    location: 't2',
    brand: 'ta',
    notes: 'Chamber at 8507 Benbrook Blvd. Gateway to 200+ area businesses. Good opening day partnership prospect.',
    createdAt: 1774390000000,
    updatedAt: 1774390000000
  },
  {
    id: 'seed_t2_2',
    name: 'Fort Worth Country Day School',
    website: 'https://www.fwcd.org',
    contact: 'Claire Ashworth',
    title: 'Office Manager',
    phone: '817-732-7718',
    email: 'info@fwcd.org',
    status: 'new',
    location: 't2',
    brand: 'ta',
    notes: 'Private school near Benbrook area. 300+ faculty & staff. Faculty meetings, event catering.',
    createdAt: 1774400000000,
    updatedAt: 1774400000000
  },
  {
    id: 'seed_t2_3',
    name: 'Texas Wesleyan University (Fort Worth)',
    website: 'https://www.txwes.edu',
    contact: 'Roy Simmons',
    title: 'Office Manager',
    phone: '817-531-4444',
    email: 'info@txwes.edu',
    status: 'new',
    location: 't2',
    brand: 'ta',
    notes: 'University with 500+ faculty & staff. Department catering, faculty events, student services.',
    createdAt: 1774410000000,
    updatedAt: 1774410000000
  },
  {
    id: 'seed_t2_4',
    name: 'Alcon (Fort Worth Manufacturing)',
    website: 'https://www.alcon.com',
    contact: 'Diana Cortez',
    title: 'HR Director',
    phone: '817-293-0450',
    email: 'hr@alcon.com',
    status: 'new',
    location: 't2',
    brand: 'ta',
    notes: 'Eye care company with large Fort Worth/Benbrook-area manufacturing. 3,000+ employees in area. Major catering account.',
    createdAt: 1774420000000,
    updatedAt: 1774420000000
  },

];

// ═══════════════════════════════════════════
// NEARBY — Real companies near each location (for map/detail view)
// ═══════════════════════════════════════════
const NEARBY_OVERRIDE = {
  j1: [
    { name: 'Concentra Health Services',      type: 'Healthcare Services',      employees: '200+' },
    { name: 'Gallagher Insurance (AJG)',       type: 'Insurance & Risk Mgmt',    employees: '200+' },
    { name: 'Click n\' Close (Mortgage)',      type: 'Mortgage / FinTech',       employees: '421' },
    { name: 'Anblicks',                        type: 'IT / Data Analytics',      employees: '568' },
    { name: 'Accolite Digital',                type: 'Digital Transformation',   employees: '5,000+' },
    { name: 'National Teachers Assoc. Life',   type: 'Insurance',                employees: '165' },
    { name: 'Guaranty Bancshares',             type: 'Banking / Financial',      employees: '488' },
    { name: 'Barrett Burke Wilson & Castle',   type: 'Law Firm',                 employees: '40+' },
  ],
  j2: [
    { name: 'Aledo ISD',                       type: 'Education',                employees: '700+' },
    { name: 'Parker County Hospital District', type: 'Healthcare',               employees: '200+' },
    { name: 'Aledo Workspace',                 type: 'Coworking / Office',        employees: '50 businesses' },
    { name: 'Walsh Ranch HOA',                 type: 'Community / Real Estate',  employees: '30+' },
    { name: 'Parker County Appraisal District',type: 'Government',               employees: '60+' },
    { name: 'Benbrook Bank',                   type: 'Banking',                  employees: '50+' },
  ],
  j3: [
    { name: 'Benbrook Area Chamber',           type: 'Business Association',     employees: '200+ members' },
    { name: 'Fort Worth ISD (SW region)',       type: 'Education',                employees: '5,000+ districtwide' },
    { name: 'Alcon Fort Worth',                type: 'Medical Devices',          employees: '3,000+ area' },
    { name: 'ANGMAR Medical Holdings',         type: 'Healthcare Management',    employees: '100+' },
  ],
  j4: [
    { name: 'Energy Square (1.1M sq ft campus)', type: 'Class A Office Campus', employees: 'Fortune 500 tenants' },
    { name: 'AT&T (N. Central Expressway)',    type: 'Telecommunications',       employees: '1,000+' },
    { name: 'Parkland Health (clinics)',       type: 'Healthcare',               employees: '10,000+ system' },
    { name: 'Axxess (Home Health Tech)',       type: 'Health Tech',              employees: '500+' },
    { name: 'Lincoln Property Company',        type: 'Real Estate',              employees: '500+' },
    { name: 'Marsh & McLennan Agency',         type: 'Insurance / Risk',         employees: '300+' },
    { name: 'BancorpSouth / Cadence Bank',     type: 'Banking',                  employees: '50+' },
  ],
  j5: [
    { name: 'Texas Health Presbyterian FM',    type: 'Hospital',                 employees: '500+' },
    { name: 'CTDI',                            type: 'Electronics / Logistics',  employees: '500+' },
    { name: 'Stryker Communications',          type: 'Medical Devices',          employees: '300-499' },
    { name: 'Likewize (formerly Brightstar)',  type: 'Device Protection Tech',   employees: '300-499' },
    { name: 'Mannatech Inc.',                  type: 'Nutritional Products',     employees: '100-299' },
    { name: 'Intellicentrics',                 type: 'Healthcare Tech',          employees: '100-299' },
    { name: 'Premier Nationwide Lending',      type: 'Mortgage',                 employees: '100-299' },
    { name: 'Whitlock (AV Tech)',              type: 'Technology',               employees: '100-299' },
  ],
  j6: [
    { name: 'TIAA (Frisco Corporate Center)',  type: 'Financial Services',       employees: '2,000+ by 2030' },
    { name: 'Thomson Reuters',                 type: 'Information Services',     employees: '300+' },
    { name: 'T-Mobile (Frisco)',               type: 'Telecommunications',       employees: '500+' },
    { name: 'PGA of America (HQ)',             type: 'Sports Org HQ',            employees: '200+' },
    { name: 'HALL Park Office Campus',         type: 'Class A Office Park',      employees: 'Multiple tenants' },
    { name: 'Toyota Financial Services',       type: 'Automotive Finance',       employees: '1,000+' },
    { name: 'Keurig Dr Pepper',                type: 'Beverage Corporate',       employees: '2,000+ area' },
  ],
  j7: [
    { name: 'Lockheed Martin Missiles & Fire Control', type: 'Aerospace / Defense', employees: '14,000+' },
    { name: 'Turbomeca USA (Safran)',           type: 'Aerospace Manufacturing', employees: '500+' },
    { name: 'Poly-America',                    type: 'Plastics Manufacturing',   employees: '1,000+' },
    { name: 'Six Flags Entertainment (HQ)',    type: 'Entertainment / Corporate', employees: '400+' },
    { name: 'Grand Prairie ISD',               type: 'Education',                employees: '2,500+' },
    { name: 'Texas Health Arlington Memorial', type: 'Hospital',                 employees: '1,000+' },
  ],
  j8: [
    { name: 'GameStop Corporation (HQ)',       type: 'Retail / Technology HQ',   employees: '1,500+' },
    { name: 'Kubota Tractor (North American HQ)', type: 'Agriculture Equipment', employees: '500+' },
    { name: 'Baylor Scott & White Grapevine',  type: 'Hospital',                 employees: '1,200+' },
    { name: 'DFW International Airport (Admin)', type: 'Aviation / Government', employees: '1,500+' },
    { name: 'Paycom Software',                 type: 'HR Tech',                  employees: '50+' },
    { name: 'Gaylord Texan Resort',            type: 'Hotel / Convention',       employees: '1,500+' },
  ],
  j9: [
    { name: 'Texas Health Presbyterian Dallas', type: 'Hospital',               employees: '2,500+' },
    { name: 'Richardson ISD (Admin)',           type: 'Education',               employees: '3,000+' },
    { name: 'State Farm (Richardson office)',   type: 'Insurance / Operations',  employees: '500+' },
    { name: 'MD Medical Group Skillman',        type: 'Medical Group',           employees: '50+' },
    { name: 'Encompass Health Rehab Hospital', type: 'Rehabilitation Hospital',  employees: '200+' },
  ],
  j10: [
    { name: 'Methodist Mansfield Medical Ctr', type: 'Hospital',                employees: '1,428' },
    { name: 'Klein Tools',                     type: 'Tool Manufacturing',       employees: '733' },
    { name: 'Mouser Electronics',              type: 'Electronics Distribution', employees: '600+' },
    { name: 'Hoffman Cabinets Inc.',           type: 'Cabinet Manufacturing',    employees: '502' },
    { name: 'BCB Transport',                   type: 'Transportation',           employees: '435' },
    { name: 'Mansfield ISD',                   type: 'Education',                employees: '3,000+' },
    { name: 'Conveyors Inc.',                  type: 'Manufacturing',            employees: '153' },
  ],
  j11: [
    { name: 'Parkland Health (NW clinics)',     type: 'Healthcare System',       employees: '10,000+ system' },
    { name: 'American Heart Association',       type: 'Nonprofit / Healthcare',  employees: '500+' },
    { name: 'Brookhaven College',               type: 'Higher Education',        employees: '1,000+' },
    { name: 'Carrollton-Farmers Branch ISD',   type: 'Education',               employees: '3,500+' },
    { name: 'CHRISTUS Health',                  type: 'Healthcare System',       employees: '500+' },
    { name: 'Nationwide Insurance (NW Dallas)', type: 'Insurance',              employees: '50+' },
  ],
  j12: [
    { name: 'Methodist Richardson Medical Ctr', type: 'Hospital',               employees: '1,500+' },
    { name: 'Garland ISD',                      type: 'Education',               employees: '5,000+' },
    { name: 'City of Sachse',                   type: 'Government',              employees: '150+' },
    { name: 'Wylie ISD',                        type: 'Education',               employees: '3,000+' },
    { name: 'Staff Perm (IT Staffing)',         type: 'Staffing / IT',           employees: '30+' },
    { name: 'Texas Health Physicians Group',    type: 'Medical Group',           employees: '50+' },
  ],
  j13: [
    { name: 'Kelly Hart & Hallman LLP',         type: 'Law Firm',                employees: '100+ attorneys' },
    { name: 'Haynes and Boone LLP',             type: 'Law Firm',                employees: '50+ attorneys' },
    { name: 'XTO Energy (ExxonMobil)',          type: 'Energy / Oil & Gas',      employees: '2,000+' },
    { name: 'American Airlines (HQ)',           type: 'Aviation HQ',             employees: '10,000+' },
    { name: 'BNSF Railway (HQ)',                type: 'Transportation HQ',       employees: '3,000+' },
    { name: 'Sundance Square Management',       type: 'Real Estate / District',  employees: '35-block district' },
    { name: 'Tarrant County Bar (area firms)',  type: 'Legal Services',          employees: '1,200+ members' },
  ],
  j14: [
    { name: 'Baylor Scott & White — Hillcrest', type: 'Hospital',               employees: '2,000+' },
    { name: 'Ascension Providence Hospital',    type: 'Hospital',                employees: '1,800+' },
    { name: 'Baylor University',               type: 'Higher Education',         employees: '3,000+' },
    { name: 'L3Harris Technologies',           type: 'Defense Manufacturing',    employees: '1,000+' },
    { name: 'HEB Grocery (Waco)',              type: 'Grocery / Distribution',   employees: '500+' },
    { name: 'McLennan Community College',       type: 'Higher Education',        employees: '500+' },
    { name: 'Brewer Science Inc.',             type: 'Semiconductor Materials',  employees: '200+' },
  ],
  t1: [
    { name: 'Brandt Engineering',              type: 'Engineering Contracting',  employees: '1,200' },
    { name: 'G6 Hospitality (Motel 6 HQ)',     type: 'Hotel Brand HQ',           employees: '500' },
    { name: 'Schneider Electric',              type: 'Automation / Energy',       employees: '574' },
    { name: 'CyrusOne Data Centers',           type: 'Data Center',              employees: '400' },
    { name: 'BuzzBallz',                       type: 'Beverage Manufacturing',   employees: '626' },
    { name: 'VRM Mortgage Services',           type: 'Mortgage Services',        employees: '375' },
    { name: 'AER Manufacturing',               type: 'Engine Components',        employees: '1,000' },
    { name: 'Western Extrusions Corp.',        type: 'Aluminum Manufacturing',   employees: '1,000' },
    { name: 'Sanmina Corporation',             type: 'Electronics Manufacturing',employees: '400' },
  ],
  t2: [
    { name: 'Benbrook Area Chamber',           type: 'Business Association',     employees: '200+ members' },
    { name: 'Alcon Fort Worth',                type: 'Medical Devices',          employees: '3,000+ area' },
    { name: 'Fort Worth Country Day School',   type: 'Private Education',        employees: '300+' },
    { name: 'Texas Wesleyan University',        type: 'Higher Education',        employees: '500+' },
  ],
};
